spring:
  thymeleaf:
#    关闭thymeleaf缓存
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/seckill?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
    hikari:
      pool-name: HikariCP
#      最小空闲连接出
      minimum-idle: 5
#      空闲连接最大存活时间
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 180000
      connection-timeout: 30000
      connection-test-query: select 1
  redis:
    connect-timeout: 10000ms
    host: 192.168.200.130
    port: 6379
    database: 0
    lettuce:
      pool:
        #最大连接数，默认8
        max-active: 1024
        #最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        #最大空闲连接
        max-idle: 200
        #最小空闲连接
        min-idle: 5
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml

logging:
  level:
#    打印mybatis-plus的sql
    com.example.seckill.mapper: debug
